### PR TITLE
Second commit

### PR DESCRIPTION
**Pull request by Seyi-Toluhi**
Hi Samuel,

This branch is almost completely different from the main branch as i have changed a lot. I also took note of things below that i am unable to fix:
1. I have hidden content using css hidden visibility but hidden content shows for a swift second when DOM loads e.g the sign in form shows under the game description section.
2. On the learn page, I want the Quiz button to call my fetchQuiz function but it wont work so i have just called the called the function standing alone on line 106.
3. Sign up form HTML validation is not effective and the form saves empty data to local storage. I am yet to setup JS form validation.
4. My generateRandom function on line 109 should not generate the same number after eachother so the quiz question is always different. It seems to not be working perfectly. 
5. I have not linked the login form to th profile page and quite frankly, i dont know how to. Would you be able to signpost me to where i can learn to do this pls?

Thank you very much for reviewing this work for me.

### CODE REVIEW

**Review by nostackdevv — CHANGES_REQUESTED** [review]
Good job creating the pull request, can you upload a video of how it works?

**Comment by Seyi-Toluhi** [comment]
Thanks samuel. Do you mean a video of my application?

**Comment by nostackdevv** [comment]
> Thanks samuel. Do you mean a video of my application?

Yeah

**Comment by Seyi-Toluhi** [comment]
https://github.com/Seyi-Toluhi/language_learning_app/assets/112572024/771ae518-536e-446f-a487-ad26d605641d

Hi Sam, sry for the delay. been trying to record and compress the video size. Here you go. Cheers

**Pull request closed without merging**
